<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Page Home</title>
        <link rel="stylesheet" href="essai.css" />
        
    </head>

    <body>
        
        <ul>
          <li class="dropdown">
                    <a href="javascript:void(0)"><img src="images/photo_essai.jpg" alt="Avatar" style="clickable"></a>
                        <div class="dropdown-content">
                          <a href="#">Mon Reseau</a>
                          <a href="#">Mes Photos</a>
                          <a href="#">Mes informations</a>
                        </div>
                </li>
                <li><a class="bouton_actif bouton", href="accueil.php">Accueil</a></li>
                <li><a class="bouton" href="messagerie.php" class="dropbtn">Messagerie</a></li>
                <li><a class="bouton" href="notifications.php">Notifications</a></li>
                <li><a class="bouton" href="emplois.php">Emplois</a></li>
            
                <li style="float:right"><a class="bouton" href="#about">Déconnexion</a></li>
        </ul>
        
        <h1>ACCUEIL - FIL D'ACTUALITE</h1>
        <p>Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.Il est considéré par de nombreux spécialistes comme le meilleur joueur de terre battue de l'histoire du tennis1,2,3, établissant en effet des records majeurs, et l'un des meilleurs joueurs de simple de tous les temps4,5,6,7. Il a remporté seize tournois du Grand Chelem et détient le record de victoires dans un tournoi majeur : celui de Roland-Garros où il s'est imposé à dix reprises, en 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2014 et 20178. Il a remporté également le tournoi de Wimbledon en 2008 et 2010, l'Open d'Australie 2009 et l'US Open 2010, 2013 et 2017. Il est ainsi le septième joueur de l'histoire du tennis à réaliser le « Grand Chelem en carrière » en simple. À ce titre, Rafael Nadal est le troisième joueur et le plus jeune à s'être imposé durant l'ère Open dans les quatre tournois majeurs sur quatre surfaces différentes, performance que seuls Roger Federer, Andre Agassi et Novak Djokovic ont accomplie. En devenant champion olympique en 2008, il est aussi le deuxième à avoir réalisé le Grand Chelem doré en carrière après Agassi. Il est aussi le seul joueur de l'histoire à avoir gagné 3 titres du Grand Chelem sur 3 types de surfaces différentes la même année (gazon, terre battue, dur). En outre, il est le seul joueur de l'histoire à avoir gagné au moins un titre du Grand Chelem chaque année pendant 10 saisons consécutives (2005-2014). Il détient le record de 31 titres en Masters 1000, il est aussi le seul à en avoir remporté 11 dans un même tournoi (Monte-Carlo 2005 à 2012, 2016 à 2018).

Il est le seul joueur à avoir obtenu dans sa carrière toutes les distinctions de l'ATP : Comeback Player of the Year (prix du retour de l'année) en 2013, Newcomer (prix du nouveau-venu) en 2003, Most Improved (joueur ayant le plus progressé) en 2005, Stefan Edberg Sportsmanship (prix du fairplay) en 2010, Arthur Ashe Humanitarian (prix humanitaire) en 2011, no 1 Mondial en 2008, 2010, 20139 et en 2017.

Après avoir été classé no 2 mondial durant 160 semaines consécutives (un record), il est no 1 mondial du 18 août 2008 au 6 juillet 2009, détrônant ainsi Roger Federer pendant quarante-six semaines. Nadal reprend la tête du classement ATP, à nouveau aux dépens de Federer, après sa victoire à Roland-Garros 2010 et l'occupe jusqu'au 3 juillet 2011, date à laquelle il retombe à la deuxième place, détrôné à son tour par Novak Djokovic à l'issue de la finale de Wimbledon 2011. Rafael Nadal redevient no 1 mondial du 7 octobre 2013 au 7 juillet 2014. Il remonte à nouveau sur la plus haute marche du podium 3 ans plus tard, le 21 août 2017, au lendemain du Masters de Cincinnati, avant de gagner son troisième US Open.

Avec l'équipe d'Espagne, il a remporté à quatre reprises la Coupe Davis. Il est médaillé d'or olympique en simple en 2008 et en double en 2016, avec Marc López.

À Roland-Garros, il présente un bilan record de 79 victoires pour 2 défaites sur la terre battue parisienne.</p>
    </body>
    
</html>